export const hsToDeleteAGuesMenu = 8;

export const karaokeListUrl =
  'https://www.youtube.com/playlist?list=PLlqbs_Cry1bjvlyP121fA5ncspCnk_dZX&jct=0PwFfHchMdOrR8-LnWgtd74Tttxyng';

export const calendarUrl = 'https://calendar.app.google/twzDcTZaSMsLMY8s5';

export const organizerPass = 'pip pip! X28 desactivada';

export const eventMapLink = 'https://maps.app.goo.gl/zDWH8ygStbV81b1TA';

/**
 * fs dont works in Vercel production env.
 * Copy-Paste the data from the "console.info" in "function loadGuestList()" in "app/list/page.tsx"
 */
export const guestListCopyPasteFromLog = [
  {
    name: 'alborfer@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'aldana.eugenia.santillan@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'alfonsomontesdeoca@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'antumaxis@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'atleticjosep@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'bichiten@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'calandrafaku@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'cardozo.infoser.2016@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'carlimarnero@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'ceciliaordonezmartinez@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'cejasfernanda219@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'chavez_karina65@hotmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'checo15487@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'cinquegranimariano@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Claudia Salvatierra <clausal7.cs@gmail.com> (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'coachingestudiio@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'cristianrinaldi1616@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'danielmaers@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'diego.jimenezbossi@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Diego Apestegui <diegohap@gmail.com>',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'dinaelizabethcheein@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'ediambra@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'eugeysalo79@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'exequielsantiago.pl@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'fabiangrohl66@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'fernandonsalomon@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'fertiberti@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'floren.vizgarra@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'florenciafarja97@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'florencialaitan1@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'gerezluiso@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'guadyarga@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'guilleceromas@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'guillehubner123@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'gustavogentile79@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'huertopaz92@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'ignajair@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'javilanger@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'jesicaescalada84@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'jjlv07@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'jmaguero5@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'jonathangabrielperez98@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'josesosapesce@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'klosrock@hotmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'lalemema22@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'leanconstantinidi@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'leotemple164@hotmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Maximiliano Lescano <lescanomaxi@gmail.com> (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'lleonardoariel21@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'loidagecchelin@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'lourdescoronel787@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'lucasmonteskaiser16@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'luchanavarro96@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'luciodigi@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'luguefi2@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'marcelotiberti@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'marcialainu@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'mariasabasta@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'marilynfsb@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'marnog22@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Martín Coronel <martinpmc@gmail.com>',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'maximiliano.umlandt@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'mayrafalcon1996@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'micaacaloso@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'monobachatero1@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Solana Montes de Oca <montesdeocasolana@gmail.com> (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'neberle235@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'nicolafveliz@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'nicolaslopezzz1998@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'noemarcelomolina@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'olezcanomattar82@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'oscarzepolmain@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'pablourtubey@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'padillavaleriadelcielo@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'paly.canceco@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'paulagenia108@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'pilarariasc@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'pons933@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'ramiro.e.ledesma@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'ramirorll@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'ricardomarhe@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'rominajimenez38011@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'sandezanarocio@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'santiagopalavecino@hotmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'silverspaceunicorn@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'thirnadia@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'valsalerno93@gmail.com (ORG)',
    isOrganizer: true,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'vanesaceciliasoria@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'vanjimvil@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'verosoldiaz87@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'vicious.rd@gmail.com (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
  {
    name: 'vulturgryphus8@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'yaquelingutierrez02@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'yesicaserrano80@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'zusalvatierra@gmail.com',
    isOrganizer: false,
    isVip: false,
    isCheckedIn: false,
  },
  {
    name: 'Luis Barrera  (VIP)',
    isOrganizer: false,
    isVip: true,
    isCheckedIn: false,
  },
];
